import co.uk.hackthetower.core.ControlCenter

/**
  * Do not edit this file without checking Scalatron documentation first
  * or your bot may stop working
  */
class ControlFunctionFactory {
  def create = new ControlCenter().processRequest _
}
